-- 계정 삭제 (모든 계정이 관련된 것을 삭제)  -> SYSTEM으로 실행
DROP USER c##test CASCADE;
-- 계정 생성하면서 할당
CREATE USER c##test IDENTIFIED BY test123 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
-- 계정 권한 설정
GRANT CONNECT, RESOURCE TO c##test;
GRANT CREATE VIEW, CREATE SYNONYM TO c##test;
GRANT UNLIMITED TABLESPACE TO c##test;
ALTER USER c##test ACCOUNT UNLOCK;
